variable "ami_id" {}
variable "instance_type" {}
variable "environment" {}
variable "vpc_id" {}
variable "key_name" {}
variable "target_arn" {}
variable "private_subnet_ids" {}
variable "alb_sg_id" {}
variable "nat" {}