version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration production --aot
  post_build:
    commands:
#      - aws s3 sync dist/my-first s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`

cache:
  paths:
    - '/root/.npm/**/*'
    
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes